const PopularCardData = [
    {
      imageUrl: "assets/images/course/course-online-01.jpg",
      title: "React Front To Back",
      rating: "5",
      reviews: "15 Reviews",
      bookmark: "Bookmark",
      author: "Angela",
      category: "Development",
      currentPrice: "$60",
      offPrice: "$120",
      link: "course-details.html",
      lessons: "12 Lessons",
      students: "50 Students",
      pText: "It is a long established fact that a reader will be distracted.",
      authorImageUrl: "assets/images/client/avatar-02.png",
      authorLink: "profile.html",
      authorCategory: "Development",
      buttonType: "learn",
      buttonText: "Learn More",
      buttonIcon: "feather-arrow-right",
      cardList2: true
    },
    {
      imageUrl: "assets/images/course/course-online-02.jpg",
      title: "PHP Beginner Advanced",
      rating: "5",
      reviews: "15 Reviews",
      bookmark: "Bookmark",
      author: "Angela",
      category: "Development",
      currentPrice: "$60",
      offPrice: "$120",
      link: "course-details.html",
      lessons: "12 Lessons",
      students: "50 Students",
      pText: "It is a long established fact that a reader will be distracted.",
      authorImageUrl: "assets/images/client/avatar-02.png",
      authorLink: "profile.html",
      authorCategory: "Development",
      buttonType: "cart",
      buttonText: "Add To Cart",
      buttonIcon: "feather-shopping-cart",
      cardList2: true
    },
    {
      imageUrl: "assets/images/course/course-online-03.jpg",
      title: "Angular Zero to Mastery",
      rating: "5",
      reviews: "5 Reviews",
      bookmark: "Bookmark",
      author: "Slaughter",
      category: "Languages",
      currentPrice: "$80",
      offPrice: "$100",
      link: "course-details.html",
      lessons: "8 Lessons",
      students: "30 Students",
      pText: "Angular Js long fact that a reader will be distracted by the readable.",
      authorImageUrl: "assets/images/client/avatar-03.png",
      authorLink: "profile.html",
      authorCategory: "Languages",
      buttonType: "learn",
      buttonText: "Learn More",
      buttonIcon: "feather-arrow-right",
      cardList2: true
    },
    {
      imageUrl: "assets/images/course/course-online-04.jpg",
      title: "Web Front To Back",
      rating: "5",
      reviews: "15 Reviews",
      bookmark: "Bookmark",
      author: "Patrick",
      category: "Languages",
      currentPrice: "$60",
      offPrice: "$120",
      link: "course-details.html",
      lessons: "20 Lessons",
      students: "40 Students",
      pText: "Web Js long fact that a reader will be distracted by the readable.",
      authorImageUrl: "assets/images/client/avater-01.png",
      authorLink: "profile.html",
      authorCategory: "Languages",
      buttonType: "learn",
      buttonText: "Learn More",
      buttonIcon: "feather-arrow-right",
      cardList2: true
    },
    {
      imageUrl: "assets/images/course/course-online-05.jpg",
      title: "SQL Beginner Advanced",
      rating: "5",
      reviews: "15 Reviews",
      bookmark: "Bookmark",
      author: "Angela",
      category: "Development",
      currentPrice: "$60",
      offPrice: "$120",
      link: "course-details.html",
      lessons: "12 Lessons",
      students: "50 Students",
      pText: "It is a long established fact that a reader will be distracted by the readable.",
      authorImageUrl: "assets/images/client/avatar-02.png",
      authorLink: "profile.html",
      authorCategory: "Development",
      buttonType: "cart",
      buttonText: "Add To Cart",
      buttonIcon: "feather-shopping-cart",
      cardList2: true
    }
  ];


  export default PopularCardData;